spring:
  datasource:
    druid:
      username: xiaotan
      password: 123456
      url: jdbc:mysql://localhost:3306/seacher?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&allowPublicKeyRetrieval=true
      drive: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.po

logging:
  level:
    com.dao: DEBUG
